server:
    port: 8081
    servlet:
        context-path: /

logging:
  level:
    root: DEBUG
    org:
      apache:
        http: DEBUG

security:
  oauth2:
    resource:
      id: 2
      token-info-uri: http://localhost:8000/oauth/introspect

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

ribbon:
  eureka:
    enabled: false

student:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:8080
