server:
  port: 8081
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8000/api/auth/introspect
    client:
      client-id: 2
      client-secret: rr2YLnbxhMC0UMBuHNvjEqNavuvTiN4DsR1kE0SR

client:
  student:
    endpoint: itebeh.herokuapp.com

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL