server:
    port: 8081
    servlet:
        context-path: /

logging:
  level:
    root: DEBUG
    org:
      apache:
        http: DEBUG

security:
  oauth2:
    client:
      client-id: ID
      client-secret: SECRET
      access-token-uri: http://localhost:8000/oauth/token
    resource:
      id: 2
      token-info-uri: http://localhost:8000/oauth/introspect
