server:
    port: 8081
    servlet:
        context-path: /

logging:
  level:
    root: DEBUG
    org:
      apache:
        http: DEBUG

security:
  oauth2:
    resource:
      id: RESOURCEID
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          PUBLIC KEY
          -----END PUBLIC KEY-----
    client:
      clientId: ID
      clientSecret: SECRET
