apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-playground-deploy
  labels:
    app: spring-boot-playground-deploy
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-playground
  template:
    metadata:
      labels:
        app: spring-boot-playground
        tier: backend
    spec:
      containers:
        - name: spring-boot-playground
          image: playground:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_ENABLED
              value: "true"
            - name: CONFIG_NAME
              value: spring-boot-playground-config
            - name: SECRETS_ENABLED
              value: "true"
            - name: SECRETS_NAME
              value: spring-boot-playground-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-playground-service
spec:
  selector:
    app: spring-boot-playground
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080
      nodePort: 30880
  type: NodePort